Repository Gong-Back/pureureum-front-end, pull requests merged in 2023-09, with the labels that each got.

#29 PRR-127 add Floating Menu in project detail page
  src/apis/project.ts
  src/assets/icons/bookmarkIcon.svg
  src/assets/icons/heartIcon.svg
  src/assets/icons/shareURLIcon.svg
  src/components/domain/Project/FloatingMenu/FloatingMenu.stories.tsx
  src/components/domain/Project/FloatingMenu/FloatingMenu.style.tsx
  src/components/domain/Project/FloatingMenu/FloatingMenu.tsx
  src/components/domain/Project/FloatingMenu/index.ts
  src/components/domain/Project/ProjecItem/ProjectItem.tsx
  src/components/domain/Project/ProjectList/ProjectList.tsx
  src/components/template/HomeTemplate/HomeTemplate.tsx
  src/constants/types/projectTypes.ts
  src/dummyData.ts
  src/pages/index.tsx
  src/utils/format.ts
Labels: 📘 Work

#32 PRR-108 Add Project Status UI
  src/components/domain/Project/ProjectOperationItem/ProjectOperationItem.style.tsx
  src/components/domain/Project/ProjectOperationItem/ProjectOperationItem.tsx
  src/components/domain/Project/ProjectOperationItem/index.ts
  src/components/template/ProjectOperationTemplate/ProjectOperationTemplate.style.tsx
  src/components/template/ProjectOperationTemplate/ProjectOperationTemplate.tsx
  src/constants/types/projectTypes.ts
Labels: 📘 Work

#34 PRR-105 Add import sorting plugin in Prettier
  .prettierrc
  package.json
  yarn.lock
Labels: 📝Suggestion

#36 PRR-113 Add Category filtering in Main page
  src/components/common/CategoryTag/CategoryTag.tsx
  src/components/domain/Main/CategoryFilter/CategoryFilter.style.tsx
  src/components/domain/Main/CategoryFilter/CategoryFilter.tsx
  src/components/domain/Main/CategoryFilter/index.ts
  src/components/template/HomeTemplate/HomeTemplate.tsx
  src/constants/project.tsx
  src/pages/index.tsx
Labels: 📘 Work

#38 PRR-126 Fix Facility Form's Button And Post API Error
  src/components/domain/MyPage/FacilityInfoForm/FacilityInfoForm.style.tsx
  src/components/template/AddFacilityTemplate/AddFacilityTemplate.style.tsx
  src/hooks/useDaumPostCode.ts
Labels: 📕 Bug

#40 PRR-82 Fix JWT System and Authentic logic
  src/apis/API.ts
  src/apis/auth.ts
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/domain/Login/LoginForm/LoginForm.tsx
  src/constants/types/authTypes.ts
  src/middleware.ts
  src/pages/_app.tsx
  src/pages/api/token.tsx
  src/pages/index.tsx
Labels: 📘 Work
