Repository Gong-Back/pureureum-front-end, pull requests merged in 2023-08, with the labels that each got.

#22 PRR-76 react-hook-form 으로 Form Migration
  package.json
  src/apis/facility.ts
  src/components/common/TextInput/TextInput.style.tsx
  src/components/common/TextInput/TextInput.tsx
  src/components/domain/Login/LoginForm/LoginForm.tsx
  src/components/domain/MyPage/FacilityInfoForm/FacilityInfoForm.style.tsx
  src/components/domain/MyPage/FacilityInfoForm/FacilityInfoForm.tsx
  src/components/domain/Register/AccountForm/AccountForm.tsx
  src/components/domain/Register/PersonalDataForm/PersonalDataForm.tsx
  src/components/domain/Register/VerifyPhoneNumberForm/VerifyPhoneNumberForm.tsx
  src/components/template/AddFacilityTemplate/AddFacilityTemplate.style.tsx
  src/components/template/AddFacilityTemplate/AddFacilityTemplate.tsx
  src/components/template/RegisterTemplate/RegisterTemplate.tsx
  src/constants/types/authTypes.ts
  src/constants/types/facilityTypes.ts
  src/hooks/useDaumPostCode.ts
  src/hooks/useUploadFile.ts
  src/pages/auth/login.tsx
  src/pages/auth/register.tsx
  src/pages/mypage/operation/apply.tsx
  src/stores/context/LoginContext.tsx
  src/stores/context/RegisterContext.tsx
  src/utils/format.ts
  yarn.lock
Labels: 📗 Refactor

#19 PRR-96 시설 생성 및 유저 프로필 API 연동 작업
  next.config.js
  package.json
  src/apis/facility.ts
  src/apis/user.ts
  src/components/common/TextInput/NewTextInput.tsx
  src/components/common/TextInput/TextInput.style.tsx
  src/components/common/TextInput/TextInput.tsx
  src/components/common/UserProfile/UserProfile.style.tsx
  src/components/domain/Login/LoginForm/LoginForm.tsx
  src/components/domain/MyPage/FacilityInfoForm/FacilityInfoForm.style.tsx
  src/components/domain/MyPage/FacilityInfoForm/FacilityInfoForm.tsx
  src/components/domain/MyPage/ProfileEditor/ProfileEditor.tsx
  src/components/domain/MyPage/UpdatePasswordModal/UpdatePasswordModal.tsx
  src/components/domain/MyPage/UpdatePhoneModal/UpdatePhoneModal.tsx
  src/components/domain/Register/AccountForm/AccountForm.tsx
  src/components/domain/Register/PersonalDataForm/PersonalDataForm.tsx
  src/components/domain/Register/VerifyPhoneNumberForm/VerifyPhoneNumberForm.tsx
  src/components/template/AddFacilityTemplate/AddFacilityTemplate.style.tsx
  src/components/template/AddFacilityTemplate/AddFacilityTemplate.tsx
  src/components/template/MyProfileTemplate/MyProfileTemplate.tsx
  src/components/template/RegisterTemplate/RegisterTemplate.tsx
  src/constants/types/authTypes.ts
  src/constants/types/facilityTypes.ts
  src/constants/types/userTypes.ts
  src/hooks/useDaumPostCode.ts
  src/hooks/useFetchProfileInfo/index.ts
  src/hooks/useFetchProfileInfo/queryKey.ts
  src/hooks/useFetchProfileInfo/useFetchProfileInfo.ts
  src/hooks/useMeasureBreakpoint.ts
  src/hooks/useUploadFile.ts
  src/pages/auth/login.tsx
  src/pages/auth/register.tsx
  src/pages/mypage/operation/apply.tsx
  src/pages/mypage/personal/profile.tsx
  src/stores/context/LoginContext.tsx
  src/stores/context/RegisterContext.tsx
  src/utils/format.ts
  yarn.lock
Labels: 📘 Work

#26 PRR-81 add project register api
  src/apis/API.ts
  src/apis/project.ts
  src/components/domain/Project/ProjecItem/ProjectItem.stories.ts
  src/components/domain/Project/ProjecItem/ProjectItem.tsx
  src/components/domain/Project/ProjectCreationForm/ProjectCreationForm.tsx
  src/components/domain/Project/ProjectList/ProjectList.tsx
  src/components/template/HomeTemplate/HomeTemplate.style.tsx
  src/components/template/ProjectCreationTemplate/ProjectCreationTemplate.tsx
  src/constants/apis/server.ts
  src/constants/types/projectTypes.ts
  src/dummyData.ts
  src/pages/index.tsx
  src/pages/project/new.tsx
Labels: 📘 Work

#27 PRR-95 react-hook-form 동작 관련 버그 수정
  next.config.js
  src/apis/facility.ts
  src/components/common/TextInput/NewTextInput.tsx
  src/components/domain/MyPage/FacilityInfoForm/FacilityInfoForm.tsx
  src/components/domain/MyPage/UpdatePasswordModal/UpdatePasswordModal.tsx
  src/components/domain/Register/AccountForm/AccountForm.tsx
  src/components/domain/Register/PersonalDataForm/PersonalDataForm.tsx
  src/components/domain/Register/VerifyPhoneNumberForm/VerifyPhoneNumberForm.tsx
  src/components/template/RegisterTemplate/RegisterTemplate.tsx
  src/constants/types/authTypes.ts
  src/constants/types/facilityTypes.ts
  src/hooks/useDaumPostCode.ts
  src/hooks/useUploadFile.ts
  src/middleware.ts
  src/utils/validation.ts
Labels: 📕 Bug

#25 PRR-93 add main project list api
  src/apis/project.ts
Labels: 📘 Work
